### ISSUE TITLE
Question about your blocklist

### ISSUE THREAD

**Issue by T145** [waelisa/Transmission-seedbox#1]
Regarding your [blocklist](https://www.wael.name/other/best-blocklist/), do you have a script to update it? The reason I ask is I'm working on https://github.com/T145/the-blacklist and would be interested in including your list if it can be actively maintained. Honestly it may not even be a bad idea to just post the whole list on your [Github](https://github.com/waelisa) to have people contribute and make issues. Thanks for your work so far!

**Comment by waelisa** [comment]
I'm sorry for late reply, but I'll upload the list here.
https://github.com/waelisa/Best-blocklist

**Comment by waelisa** [comment]
Close
